theme: jekyll-theme-minimal

## Welcome to my blog I'm
Name:Taehwan jang
Lab :Network Data Science Lab
University: Sangmyung University
Research Assistant

# PROJECTS

###Programming Language

- java
- python
- c

